### ISSUE TITLE
Attributes 2.02.185 not being pulled with the chef-ruby-lvm-attrib gem version 0.2.7

### ISSUE THREAD

**Issue by kalyani9s** [chef/chef-ruby-lvm-attrib#16]
We use GitHub issues to track bugs and feature requests. If you need help please post to our Mailing List or join the Chef Community Slack.

 * Chef Community Slack at http://community-slack.chef.io/.
 * Chef Mailing List https://discourse.chef.io/

Attributes 2.02.185 not being pulled with the chef-ruby-lvm-attrib gem version 0.2.7 

 ArgumentError: Unable to load lvm attributes [lvs.yaml] for version [2.02.185(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-ruby-lvm-attrib-0.2.7/lib/lvm/attributes/2.02.185(2)/lvs.yaml]

I get this error it does'nt list in the attributes , see below 

![image](https://user-images.githubusercontent.com/53915482/62729375-d09e5000-b9eb-11e9-87dc-448cd3927b44.png)

Also, one more question; I think the attributes version is getting incremented regularly; like we had 2.02.180 recently; but then its now expecting 2.02.185 ; I believe this from `LVM2 PACKAGE` ... if this attribute version keep changing it would affect our infrastructure run on server.  
Is there a way to maintain at one stable version of attributes for the gem installed ?

 Support issues opened here will be closed and redirected to Slack or Discourse.

**Comment by tas50** [comment]
I've release 0.2.8 which includes that version
