### ISSUE TITLE
Unable to load lvm attributes [lvs.yaml] for version [2.02.185(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-attrib-0.2.7/lib/lvm/attributes/2.02.185(2)/lvs.yaml]

### ISSUE THREAD

**Issue by bbangka** [chef/chef-ruby-lvm-attrib#17]
# Version: 0.2.7

[Version of the project installed]

# Environment:RHEL 7.7

[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario: I'm running lvm cookbook, and I get the following error:
"Unable to load lvm attributes [lvs.yaml] for version [2.02.185(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-attrib-0.2.7/lib/lvm/attributes/2.02.185(2)/lvs.yaml]"

ls /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-attrib-0.2.7/lib/lvm/attributes/ 

2.02.100(2)  2.02.118(2)  2.02.136(2)  2.02.154(2)  2.02.172(2)      2.02.74(2)
2.02.101(2)  2.02.119(2)  2.02.137(2)  2.02.155(2)  2.02.173(2)      2.02.83(2)
2.02.102(2)  2.02.120(2)  2.02.138(2)  2.02.156(2)  2.02.175(2)      2.02.84(2)
2.02.103(2)  2.02.121(2)  2.02.139(2)  2.02.157(2)  2.02.176(2)      2.02.86(2)
2.02.104(2)  2.02.122(2)  2.02.140(2)  2.02.158(2)  2.02.177(2)      2.02.87(2)
2.02.105(2)  2.02.123(2)  2.02.141(2)  2.02.159(2)  2.02.178(2)      2.02.88(2)
2.02.106(2)  2.02.124(2)  2.02.142(2)  2.02.160(2)  2.02.178(2)-rc1  2.02.95(2)
2.02.107(2)  2.02.125(2)  2.02.143(2)  2.02.161(2)  2.02.179(2)      2.02.96(2)
2.02.108(2)  2.02.126(2)  2.02.144(2)  2.02.162(2)  2.02.180(2)      2.02.97(2)
2.02.109(2)  2.02.127(2)  2.02.145(2)  2.02.163(2)  2.02.181(2)      2.02.98(2)
2.02.110(2)  2.02.128(2)  2.02.146(2)  2.02.164(2)  2.02.182(2)      2.02.99(2)
2.02.111(2)  2.02.129(2)  2.02.147(2)  2.02.165(2)  2.02.183(2)      2.03.00(2)
2.02.112(2)  2.02.130(2)  2.02.148(2)  2.02.166(2)  2.02.26          2.03.01(2)
2.02.113(2)  2.02.131(2)  2.02.149(2)  2.02.167(2)  2.02.27
2.02.114(2)  2.02.132(2)  2.02.150(2)  2.02.168(2)  2.02.29
2.02.115(2)  2.02.133(2)  2.02.151(2)  2.02.169(2)  2.02.30
2.02.116(2)  2.02.134(2)  2.02.152(2)  2.02.170(2)  2.02.54(1)
2.02.117(2)  2.02.135(2)  2.02.153(2)  2.02.171(2)  2.02.66(2)

It's missing 2.02.185(2)

**Comment by kalyani9s** [comment]
Hi, looks like I have opened a similar issue just few minutes same ; infact same. Hoping to see some response from the community .

**Comment by bootswithdefer** [comment]
It looks like the attributes were committed in https://github.com/chef/chef-ruby-lvm-attrib/pull/13

There just needs to be a new version of the gem released that includes it.

**Comment by tas50** [comment]
I pushed up 0.2.8
