### ISSUE TITLE
Attributes need to be updated for 2.02.186(2)

### ISSUE THREAD

**Issue by bootswithdefer** [chef/chef-ruby-lvm-attrib#24]
# Version:

0.2.8

# Environment:

RHEL7.8

# Scenario:

Running the sensu-plugins-lvm check-lv-usage.rb script (https://github.com/sensu-plugins/sensu-plugins-lvm/blob/master/bin/check-lv-usage.rb) on the newly released RHEL7.8 throws an error.

# Steps to Reproduce:

Run check-lv-usage.rb on RHEL7.8

# Expected Result:

volume list processed by Sensu

# Actual Result:

Unable to load lvm attributes [lvs.yaml] for version [2.02.186(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/chef-ruby-lvm-attrib-0.2.8/lib/lvm/attributes/2.02.186(2)/lvs.yaml]

**Comment by ehuizar1028** [comment]
I am also getting this same error while attempting to extend a LVM group while using Chef's supermarket cookbook. Small workaround is copying 185 and rename to 186 (not optimal, but it works as a temp workaround).

https://supermarket.chef.io/cookbooks/lvm

**Comment by vsoloviov** [comment]
+1, has the same with lvm cookbook

**Comment by tas50** [comment]
I've updated the attributes with 2.03. 2.02.186 was actually already up in the 0.3.0 gem. I also updated the cookbook on the supermarket to pull in the new 0.3.1 gem version. Feel free to open this back up if you're still seeing issues.
