### ISSUE TITLE
Rubygem 0.3.7

### ISSUE THREAD

**Issue by ianl678** [chef/chef-ruby-lvm-attrib#35]
Hi,

I see the PR for 0.3.7 back in Jan '21 but it's not reflected in rubygems yet, how does it get promoted there?

https://rubygems.org/gems/chef-ruby-lvm-attrib

Thanks

**Comment by ianl678** [comment]
Has now been updated

**Comment by GATWE** [comment]
Welcows Chefe One Microsoft way : Rede Mond
